### ISSUE TITLE
screenshots missing

### ISSUE THREAD

**Issue by mmiat** [paginagmbh/redmine_lightbox2#11]
the screenshots in these pages:
https://github.com/paginagmbh/redmine_lightbox2
https://github.com/paginagmbh/redmine_lightbox2/tree/redmine-2.6
are missing: 404 not found error

**Comment by tofi86** [comment]
thanks for notifying me. they were still hotlinked from the original repository...
will take new screenshots soon...

**Comment by tofi86** [comment]
removed the screenshots with 21daa84f7e77c375f51a356ce78b593336a024be on `master` and with 22465efaeb8cc5337b2365c98be560ba62e4b038 on `redmine-2.6`

Won't post new screenshots at the moment...
