### ISSUE TITLE
Compatibility with RedmineCRM contacts plugin

### ISSUE THREAD

**Issue by madc** [paginagmbh/redmine_lightbox2#12]
Adding `.avatar a` to the js facybox selector in `assets/javascript/lightbox.js` yould make this plugin compatible with the RedmineCRM contacts plugin.

    $(".avatar a, div.attachments a.lightbox, div.attachments a.swf").fancybox({

**Comment by tofi86** [comment]
Fixed with latest version for redmine 3.x.

However, this is **untested** as I don't have a license of the RedmineCRM Contacts plugin...
