### ISSUE TITLE
PDF preview doesn't work if the file extension is written in capital letters (.PDF)

### ISSUE THREAD

**Issue by sbaatar** [paginagmbh/redmine_lightbox2#16]
PDF preview doesn't work if the file extension is written in in capital letters (.PDF) and the preview icon gets bigger. On the screenshot below the PDF files are the same, except their file names.
![pdf extension issue](https://cloud.githubusercontent.com/assets/15318106/10721597/60153f0c-7be1-11e5-913d-94e817f7892b.png)

**Comment by tofi86** [comment]
I can reproduce with Redmine 3.1.1.stable.14618

Seems to be a Redmine bug as they generate different CSS classes: `pdf` and `PDF` - but CSS is case sensitive!

Will see whether I can fix it with a workaround...

**Comment by tofi86** [comment]
Fixed for redmine 2.6.x

**Comment by tofi86** [comment]
Fixed for redmine 3.x
New version out soon...
