### ISSUE TITLE
attachment previews are broken

### ISSUE THREAD

**Issue by ianchan** [paginagmbh/redmine_lightbox2#21]
I'm not sure if this is a problem with this plugin but I thought I'd start here. The lightbox works correctly for attachments but the path for the src attribute for the thumbnail image is broken.The problem is that the path to the thumbnail image repeats the base folder of the Redmine location.

So the broken source path look like this /base/base/attachments/thumbnail/249. 
However, the correct path should be /base/attachments/thumbnail/249. 

The thumbnails are being generated and can be accessed if the path is corrected to remove the extra directory.

Thanks for your help.

**Comment by tofi86** [comment]
Which Redmine version are you using?

Which plugin version are you using?

Do you mean thumbnails in issue notes or wiki pages or thumbnails of attachments?

**Comment by ianchan** [comment]
These are the thumbnails for files attached to issues.
The following is from the Information section of Redmine Admin.

Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p247 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.11
  Mercurial                      2.2.2
  Git                            2.0.5
  Filesystem                     
Redmine plugins:
  a_common_libs                  1.1.3
  advanced_roadmap_v2            2.4.1
  clipboard_image_paste          1.10
  custom_menu                    1.0.0
  project_section                0.0.2
  redmine__select2               1.0.5
  redmine_admin_monitor          1.0.0
  redmine_agile                  1.3.8
  redmine_auto_percent           0.0.1
  redmine_charts2                0.2.1
  redmine_checklists             3.0.4
  redmine_customize              1.1.0
  redmine_extended_watchers      1.0.5
  redmine_hipchat                2.0.0
  redmine_lightbox2              0.1.3
  redmine_local_avatars          0.0.2
  redmine_sidebar_toc            0.0.1
  redmine_silencer               0.4.0
  redmine_simple                 1.1.8
  redmine_stats                  0.0.2
  rmp_group_watchers             1.0.0
  sidebar_hide                   0.0.7
  simple_author_change           0.0.4

**Comment by tofi86** [comment]
Please update to the latest version of my plugin, released yesterday.

I cannot support outdated versions of my plugin.

If you can, please update your Redmine installation to the latest 2.6.x release.

**Comment by tofi86** [comment]
After applying the update(s), does it still happen?

**Comment by tofi86** [comment]
Have you been able to test with the latest plugin version?

**Comment by ianchan** [comment]
Thanks for following-up. I am waiting to update Redmine when no one is using the system.

**Comment by shaungilroy** [comment]
This may or may not be related here, but what I'm experiencing, having installed this lovely plugin today is that existing image uploads have no thumbnail. New images I upload after the upgrade, however, have thumbnails.

It might be a nice feature to add a migration that generates thumbs for existing attachments.

**Comment by tofi86** [comment]
*@shaungilroy wrote:*
> It might be a nice feature to add a migration that generates thumbs for existing attachments.

This is out of scope of this plugin... It doesn't "generate" thumbnails at all.

The PlugIn just uses the given thumbnails, or, if redmine cannot generate thumbnails, shows a scaled version of the original image as preview.

**Comment by shaungilroy** [comment]
Got it. In that case, thumbnails are working file for me.

**Comment by tofi86** [comment]
@ianchan any news? is the plugin working for you after you updated the system? I'm closing this now, feel free to reopen if the issue still exists...
