### ISSUE TITLE
Fancy box not render image correctly when image resolution is too large

### ISSUE THREAD

**Issue by virudson** [paginagmbh/redmine_lightbox2#22]
I'm using Redmine version 3.1.1

The preview is okay but not for popup. look like it's not render correctly.

http://i.imgur.com/cKHDU9U.png

**Comment by tofi86** [comment]
What is the size of the image?

**Comment by virudson** [comment]
It's 2160 × 1176

**Comment by tofi86** [comment]
Unfortuantely, I cannot reproduce with Redmine 3.1.3 and plugin version 0.2.4.
Neither in Chrome nor in Firefox on a Retina MacBook.
This is how it looks in Chrome: Resized as it should be...

![bildschirmfoto 2015-12-29 um 22 57 16](https://cloud.githubusercontent.com/assets/365118/12042891/cefb8982-ae7f-11e5-9a8b-523aebf5e75d.png)

Which plugin version do you use? Are you running the latest v0.2.4? Can you upgrade your Redmine to at least 3.1.3?

**Comment by virudson** [comment]
I upgrade it to latest version. and it's work just fine. Thank you ;-)
