### ISSUE TITLE
Lightbox not working on thumbnails in issue history

### ISSUE THREAD

**Issue by Atmis** [paginagmbh/redmine_lightbox2#23]
Hello,

Redmine 3.2 introduced a thumbnail display in the issue history (this replaces the Inline note images plugin). See : http://www.redmine.org/issues/13429

But when we click on that thumbnail, the lightbox does not show up.

Is it possible to fix it ?

Thanks a lot for your very useful plugin.

**Comment by tofi86** [comment]
Will have a look soon...

**Comment by tofi86** [comment]
Done. Will be included in the next updated.
