### ISSUE TITLE
Preview not working with Redmine 3.3

### ISSUE THREAD

**Issue by Atmis** [paginagmbh/redmine_lightbox2#25]
Hello,

The plugin seems to be broken when displaying thumbnails and image previews with Redmine 3.3

I guess this is due to that change in Redmine :
http://www.redmine.org/issues/22058

Thank you

Pierre

**Comment by tofi86** [comment]
Thanks for reporting this. I will have a look soon :)

**Comment by archonwang** [comment]
+1 
in Redmine 3.3, it seems not worked when previewing.

**Comment by archonwang** [comment]
@tofi86 , I have found an branch that support thumbnails preview on redmine 3.3, could you check it ,thanks.

I tested it on my environment is ok
https://github.com/endocode/redmine_lightbox2/commit/2b4fa579e544c70682dae110dad191c50ee51a97

**Comment by tofi86** [comment]
I would not suggest to use a branch from 2015 which eventually works now with 3.3

I already did some testing and will release a new version within the next week.
Stay tuned...

**Comment by archonwang** [comment]
@tofi86 , Thanks for your replies.

unfortunately, I tested the branch further more, and found it still contains some error...

**Comment by dstana** [comment]
+1 on this, looking forward to the update.

Thank you.

**Comment by maximkrusina** [comment]
+1

**Comment by xyz37** [comment]
I exam log file.

> E, [2016-06-28T15:22:13.204813 #6072] ERROR -- : Creating thumbnail failed (pid 372 exit 1):
> Command: "D:/CI/ImageMagick/convert.exe" "D:/CI/redmine/files/2016/06/160628152212_picture377-1.png" -thumbnail "100x100>" "D:/CI/Redmine/tmp/thumbnails/243_491b66b1d8d9438f1b5eccdaebf5cfc6_100.thumb"


then I execute convert.exe in command line .
and i was an error **"missing an image filename"**

> "D:/CI/ImageMagick/convert.exe" "D:/CI/redmine/files/2016/06/160628152212_picture377-1.png" -thumbnail "100x100>" "D:/CI/Redmine/tmp/thumbnails/243_491b66b1d8d9438f1b5eccdaebf5cfc6_100.thumb"
> convert.exe: no decode delegate for this image format `D:/CI/redmine/files/2016/06/160628152212_picture377-1.png' @ constitute.c/ReadImage/503.
> convert.exe: missing an image filename `D:/CI/Redmine/tmp/thumbnails/243_491b66b1d8d9438f1b5eccdaebf5cfc6_100.thumb' @ convert.c/ConvertImageCommand/2822.

maybe redmine thumbnail.rb pass some parameter

**Comment by tofi86** [comment]
Did some first coding this evening.

Now that redmine has introduced the magnifier icon
<img width="614" alt="bildschirmfoto 2016-06-28 um 23 39 14" src="https://cloud.githubusercontent.com/assets/365118/16433285/ba377eea-3d89-11e6-8b4d-33d74ff70525.png">
would you expect this to be the "open lightbox" link?

Previously we had a separate icon for that (black eye):
<img width="429" alt="bildschirmfoto 2016-06-28 um 23 38 28" src="https://cloud.githubusercontent.com/assets/365118/16433303/d84ed5ae-3d89-11e6-81a7-7a619716943d.png">

I want to keep the image name as download link and either the magnifier icon or the old black eye icon as lightbox link.

All thumbnails / previews will open in lightbox view anyways...

**Comment by Atmis** [comment]
Thanks for looking at this.

In my opinion, it would be more consistent to use the magnifier icon.

**Comment by dstana** [comment]
Are these icons currently working now? I'm seeing a failed image where these are supposed to be with lightbox installed.

**Comment by tofi86** [comment]
@Atmis okay, thanks for your feedback

@dstana no, haven't committet my code changes yet. Just wanted to ask for your feedback on which icon to use.

When using the magnifier icon link introduced by Redmine 3.3 we would loose the "view image on separate page" function which was added with 3.3.
But IMHO it's more convenient to view the image in lightbox than on a different page, so yes, I'm also in favor of changing the behaviour of the redmine magnifier icon link.

**Comment by dstana** [comment]
Yes, I think using the magnifier icon makes sense. With the lightbox the viewing on another page is obsolete. 

I was just trying to make sure I hadn't misconfigured anything or that I had something else going on that could be causing an issue because the magnifying glass isn't visible for me know.

**Comment by tofi86** [comment]
> because the magnifying glass isn't visible for me know.

yeah, that's because the lightbox plugin overrides the new redmine 3.3 code.

stay tuned guys! :)

**Comment by tofi86** [comment]
So here we go, Redmine 3.3 support has landed on master branch.
Please give it a go and report regressions! But I'm positive that' everything works as expected!

Support for Redmine 3.0-3.2 can be found on a separate branch now...

Have fun!

**Comment by archonwang** [comment]
wow.thanks

**Comment by Atmis** [comment]
Works like a charm ! Thanks a lot !

**Comment by tofi86** [comment]
@Atmis great, glad to hear that! :)

**Comment by d-led** [comment]
works superbly, thanks! 
There's another issue: the thumbnail macro is still broken: `{{thumbnail(image.png)}}`

**Comment by tofi86** [comment]
@d-led happy to hear that!

And for the other issue, please open a new ticket. Thanks.

**Comment by d-led** [comment]
@tofi86 thanks! Done
