### ISSUE TITLE
The thumbnail macro doesn't work in Redmine 3.3

### ISSUE THREAD

**Issue by d-led** [paginagmbh/redmine_lightbox2#28]
While the attachment functionality has been fixed by the recent version, the thumbnail macro `{{thumbnail(image.png)}}` doesn't seem to work yet.

Redmine config:

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.0.0-p645 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.13
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  advanced_roadmap_v2            2.4.2
  redmine_agile                  1.4.1
  redmine_codebutton             0.1.0
  redmine_graphs                 0.1.0
  redmine_issue_completion       0.0.2
  redmine_issue_history          1.0.0
  redmine_issue_templates        0.1.2
  redmine_lightbox2              0.3.0
```

**Comment by tofi86** [comment]
Where do you use the thumbnail macro? On issue description, or on issue notes or on a wiki page?

**Comment by tofi86** [comment]
Alright, confirmed! Will be fixed with 0.3.1 in a couple of minutes...

**Comment by d-led** [comment]
it works. Many thanks!

**Comment by tofi86** [comment]
Great, you're welcome!

**Comment by FutureLinkOpenSource** [comment]
We see this issue still in 0.3.1 with Redmine 3.3.2. Clicking on a thumbnail in a wiki page generated by the {{thumbnail(filename, size=x, Title=Foo)}} macro will return a 404 response. For some reason, version 0.3.1 of this plugin is using the attachment title set in the thumbnail macro instead of the file name itself:

> Started GET "/attachments/download/4163/Bottom%20of%20rack%20-%20rear%20view" for 127.0.0.1 at 2017-01-26 10:35:53 -0400
> Processing by AttachmentsController#download as HTML
>   Parameters: {"id"=>"4163", "filename"=>"Bottom of rack - rear view"}
>   Current user: test_user (id=9001)
>   Rendered common/error.html.erb within layouts/base (0.2ms)
>   Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.1ms)
>   Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.1ms)
> Filter chain halted as :find_attachment rendered or redirected
> Completed 404 Not Found in 44ms (Views: 25.7ms | ActiveRecord: 12.7ms)

This is limited to the lightbox2 plugin, as removing the plugin and clicking on the attachment link will display the image. If this is fixed in master, could we please get a new version of the package tagged?

**Comment by tofi86** [comment]
> We see this issue still in 0.3.1 with Redmine 3.3.2.

Please see #33 for further discussion!

**Comment by robertfausk** [comment]
Will this one also be fixed for redmine 3.2? In tag 0.2.8 e.g.?
I currently have redmine installed via ubuntu 16.04 package manager.

**Comment by tofi86** [comment]
@robertfausk see #36

**Comment by tofi86** [comment]
Note: _This fix has been backported without testing to the `redmine-3.0-3.2` branch for Redmine 3.0-3.2 by request of @robertfausk.  Please see #36 for further discussion._
