### ISSUE TITLE
Zoom/Scroll

### ISSUE THREAD

**Issue by jsh562** [paginagmbh/redmine_lightbox2#30]
Large resolution images show up in the preview already very zoomed in and it only has vertical scrollbars.

**Comment by tofi86** [comment]
probably related to #22 ?

Do you have the latest plugin version installed? Which one?

Which redmine version do you use?

Can you post a screenshot so I can better understand what the problem is?

**Comment by jsh562** [comment]
I believe it is the same as #22
Updating to the latest version is not possible for me because we are on redmine 3.0.3 at the moment.

**Comment by tofi86** [comment]
Okay...
Do you at least use the latest plugin version 0.2.7 from the `redmine-3.0-3.2` branch of thisrepository?

**Comment by jsh562** [comment]
I just updated to 0.2.7 and tested and it works fine. Thank you.
