### ISSUE TITLE
My redmine_lightbox2 0.3.1 not working with Redmine 3.3

### ISSUE THREAD

**Issue by BezQ** [paginagmbh/redmine_lightbox2#31]
I can not see any lightbox in issues. What would I check to find conflict plugin?

> Environment:
> Redmine version                3.3.0.stable
> Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
> Rails version                  4.2.6
> Environment                    production
>  Database adapter               Mysql2
> SCM:
> Git                            2.1.4
> Filesystem  
> Redmine plugins:
> redmine_agile                  1.4.0
> redmine_checklists             3.1.3
> redmine_custom_js              0.1.0
> redmine_default_custom_query   1.1.2
> redmine_lightbox2              0.3.1

**Comment by tofi86** [comment]
did you follow the installation instructions to the point? Meaning, running the `rake redmine:plugins:migrate RAILS_ENV=production` from the redmine *root* directory?

> What would I check to find conflict plugin?

Disable all your plugins temporarily and re-enable one after the other... This should help finding the conflicting plugin.

**Comment by mmiat** [comment]
me too, I don't know since it doesn't work any more, I've noticed today after months from last update

the images linked with thumbnail tag open the link, while the list of attachment in bottom of the page works

if can be useful, the html is:

NOT WORKING IN WIKI PAGE
`<a class="thumbnail" title="rbi.PNG" href="/attachments/479/rbi.PNG"><img alt="rbi.PNG" src="/attachments/thumbnail/479"></a>`

WORKING AT THE BOTTOM OF THE PAGE
`<a class="icon-only icon-magnifier lightbox_preview png" rel="attachments" title="rbi.PNG" href="/attachments/download/479/rbi.PNG">Mostra</a>`

**Comment by tofi86** [comment]
It works very well in my dev installation as you can see here:

<img width="786" alt="bildschirmfoto 2017-01-19 um 18 49 09" src="https://cloud.githubusercontent.com/assets/365118/22118450/1e7e3170-de78-11e6-84fe-1639353a6344.png">

code for inserting thumbnail I used is `{{thumbnail(test.png)}}`

I have a couple of questions for you:
* are you using version 0.3.1 of my plugin?
* Please copy ALL of the information from `http://your-host.tld/admin/info` starting from `Environment: …`
* are you using the "Standard" theme or another?
* How did you insert the thumbnail in the wiki?
* are you using textile or markdown markup in your redmine installation?

**Comment by Arno234** [comment]
I have an identical problem : plugin is detected, but nothing changes on my ticket view... is there something to activate ?
my infos : 

Redmine 3.3.1.stable
Compte administrateur par défaut changé 	
Répertoire de stockage des fichiers accessible en écriture 	
Répertoire public des plugins accessible en écriture (./public/plugin_assets) 	
Bibliothèque RMagick présente (optionnelle) 	
Binaire convert de ImageMagick présent (optionel) 	

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.17
  Filesystem                     
Redmine plugins:
  redmine_lightbox2              0.3.1

**Comment by Arno234** [comment]
I have an identical problem : plugin is detected, but nothing changes on my ticket view... is there something to activate ?
my infos : 

Redmine 3.3.1.stable
Compte administrateur par défaut changé 	
Répertoire de stockage des fichiers accessible en écriture 	
Répertoire public des plugins accessible en écriture (./public/plugin_assets) 	
Bibliothèque RMagick présente (optionnelle) 	
Binaire convert de ImageMagick présent (optionel) 	

Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.17
  Filesystem                     
Redmine plugins:
  redmine_lightbox2              0.3.1

**Comment by tofi86** [comment]
@Arno234 please provide more details. Are you using the thumbnail macro and missing the lightbox? Or where are you expecting the lightbox to show and it doesn't?

**Comment by Arno234** [comment]
My problem is that I attach image files to demands, and nothing changes on viewing images (think that's what you name image thumbnail) : 

![view](https://cloud.githubusercontent.com/assets/25369784/22362969/1d5bc2b8-e467-11e6-826e-a5caa2712ded.png)

**Comment by tofi86** [comment]
@Arno234 no, what I meant with thumbnail macro is the _macro_ function for creating thumbnails: `{{thumbnail(image.png}}`. But apparently that's not what you're using...

Do you have "Display attachment thumbnails" enabled or disabled in Redmine Settings -> Display ? Anyways, there should be a DIV rendered beneath the list of images. See web inspector screenshot: 

<img width="733" alt="bildschirmfoto 2017-01-28 um 19 11 52" src="https://cloud.githubusercontent.com/assets/365118/22398685/cd89e774-e58d-11e6-8925-d21782960fa2.png">

Can you confirm that the DIV is missing? Or probably your theme just hides it?

**Comment by Arno234** [comment]
Well, sorry, i do not handle/understand macro on this environment (is this ruby ?).
I've enabled the dispaly attachement thumbnails, and the thumbnail div appears at the bottom, but without "image" class. Then, clicking on it keeps the redmine default behaviour. 

![image](https://cloud.githubusercontent.com/assets/25369784/22415086/bcfae768-e6c4-11e6-9e6a-997634e31279.png)

**Comment by Arno234** [comment]
...i am using "default" redmine theme...

**Comment by tofi86** [comment]
> I've enabled the dispaly attachement thumbnails, and the thumbnail div appears at the bottom, but without "image" class. Then, clicking on it keeps the redmine default behaviour.

Okay, than in this case, the lightbox script is not loaded which means you did not install the plugin correctly. Did you follow the installation instructions _to the point?_

**Comment by Arno234** [comment]
RIGHT !!! i've missed the name of the folder ... working perfectly now !
Thanks very much for your help :)

**Comment by tofi86** [comment]
Great, good to hear!

Because @BezQ and @mmiat didn't respond anymore, I'm closing this ticket.
