### ISSUE TITLE
Cannot open images

### ISSUE THREAD

**Issue by vvklymchuk** [paginagmbh/redmine_lightbox2#32]
Sometimes when I open image preview I get this popup message: "The requested content cannot be loaded. Please try again later." Is it because the name of an image has Cyrillic symbols?
After many times of reloading page such images can be open. 
Below is a part of log file when I opened image.
Version:
Redmine: 3.2.0-stable
Ruby: 2.1.7
LightBox: 0.2.5

```SQL
Processing by AttachmentsController#show as */*

Parameters: {"id"=>"238", "filename"=>"\xD0\xBF\xD0\xBE\xD0\xBC_16_3.jpg"}
UPDATE `tokens` SET `tokens`.`updated_on` = '2016-11-17 15:18:55' WHERE `tokens`.`user_id` = 1 AND `tokens`.`value` = 'ad87a462a1xxxxf467ea0d7bxxxx246e070f9fcb' AND `tokens`.`action` = 'session' AND 
SELECT MAX(`settings`.`updated_on`) FROM `settings`
SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('User', 'AnonymousUser', 'Person') AND `users`.`status` = 1 AND `users`.`id` = 1 LIMIT 1

Current user: admin (id=1)
SELECT MAX(`contacts_settings`.`updated_on`) FROM `contacts_settings`
SELECT  `attachments`.* FROM `attachments` WHERE `attachments`.`id` = 238 LIMIT 1

Rendered common/error.html.erb within layouts/base (0.0ms)
SELECT  `user_preferences`.* FROM `user_preferences` WHERE `user_preferences`.`user_id` = 1 LIMIT 1 Rendered inline template (0.0ms)
SELECT `projects`.`id`, `projects`.`name`, `projects`.`identifier`, `projects`.`lft`, `projects`.`rgt` FROM `projects` INNER JOIN `members` ON `projects`.`id` = `members`.`project_id` WHERE `members`.`user_id` = 1 AND (projects.status<>9) AND `projects`.`status` = 1

Filter chain halted as :find_attachment rendered or redirected
Completed 404 Not Found in 31ms (Views: 31.2ms | ActiveRecord: 0.0ms)
```

**Comment by tofi86** [comment]
Please update to version 0.2.7 from `redmine-3.0-3.2` branch (https://github.com/paginagmbh/redmine_lightbox2/tree/redmine-3.0-3.2).

However, I have never heard of such problems and I think this isn't a fault in my plugin, because as you note, it works (sometimes)...

Do you see any JavaScript errors on Chrome/Firefox Developer Console?

**Comment by vvklymchuk** [comment]
> Please update to version 0.2.7 from redmine-3.0-3.2 branch
As I see v0.2.6 and v0.2.7 have no changes in files except version, am I right?

> I think this isn't a fault in my plugin
I agree that the problem can be not in the plugin, but I don't know where do I need to dig into.

> Do you see any JavaScript errors on Chrome/Firefox Developer Console?
Only errors HTTP 404 Not Found for jpg files when I clicked preview.

**Comment by tofi86** [comment]
> As I see v0.2.6 and v0.2.7 have no changes in files except version, am I right?

Absolutely, sorry! Haven't had that in mind anymore... ;-)

To be able to test and reproduce, can you please paste the name of the image? When trying to decode the given string from your logfile I only get `Ð¿Ð¾Ð¼_16_3.jpg` which doesn't seem to be cyrillic...

**Comment by vvklymchuk** [comment]
I have three images attached to an issue with names
пом_16_1.jpg
пом_16_2.jpg
пом_16_3.jpg
What is strange that files can be open or not in random order.)
Thank you for response

**Comment by tofi86** [comment]
I don't have my dev installation around at the moment, but with my live system (redmine 3.3.1 and lightbox 0.3.1) I cannot reproduce the problem... Neither in Firefox nor in Chrome nor in Opera...

![screenshot](https://cloud.githubusercontent.com/assets/365118/20484607/394d3752-aff8-11e6-8d82-d76e991f094c.png)

**Comment by vvklymchuk** [comment]
OK, thanks.
I will try to find a solution in redmine code (settings)

**Comment by tofi86** [comment]
Sorry for not beeing able to help you with that! :-(
