### ISSUE TITLE
Thumbnails with titles do not open in lightbox

### ISSUE THREAD

**Issue by tofi86** [paginagmbh/redmine_lightbox2#33]
_@FutureLinkOpenSource wrote in https://github.com/paginagmbh/redmine_lightbox2/issues/28#issuecomment-275414404_

> We see this issue still in 0.3.1 with Redmine 3.3.2. Clicking on a thumbnail in a wiki page generated by the `{{thumbnail(filename, size=x, Title=Foo)}}` macro will return a 404 response. For some reason, version 0.3.1 of this plugin is using the attachment title set in the thumbnail macro instead of the file name itself:
> 
>     Started GET "/attachments/download/2314/Bottom%20of%20rack%20-%20rear%20view" for 127.0.0.1 at 2017-01-26 10:35:53 -0400
>     Processing by AttachmentsController#download as HTML
>     Parameters: {"id"=>"2314", "filename"=>"Bottom of rack - rear view"}
>     Current user: test_user (id=9001)
>     Rendered common/error.html.erb within layouts/base (0.2ms)
>     Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (0.1ms)
>     Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.1ms)
>     Filter chain halted as :find_attachment rendered or redirected
>     Completed 404 Not Found in 44ms (Views: 25.7ms | ActiveRecord: 12.7ms)
> 
> This is limited to the lightbox2 plugin, as removing the plugin and clicking on the attachment link will display the image. If this is fixed in master, could we please get a new version of the package tagged?

The bug can be reproduced in Redmine 3.3.2 when using the thumbnail macro with title attribute:

```
{{thumbnail(filename, size=x, Title=Foo)}}
```

**Comment by tofi86** [comment]
this is fixed on the `master` branch with 89aad68

@FutureLinkOpenSource would you please confirm that this works for you before I release a new version?

**Comment by FutureLinkOpenSource** [comment]
Work great. Thank you very much for the fixes. Will update the package in pkgsrc once a new version is tagged.

**Comment by tofi86** [comment]
great, thanks for testing! 👍 
new version will be released soon...

**Comment by FutureLinkOpenSource** [comment]
Thanks! Do you have an estimation of when that might be?

**Comment by tofi86** [comment]
Just tagged the new release: https://github.com/paginagmbh/redmine_lightbox2/releases/tag/v0.3.2

Have fun!

**Comment by tofi86** [comment]
Note: _This fix has been backported without testing to the `redmine-3.0-3.2` branch for Redmine 3.0-3.2 by request of @robertfausk.  Please see #36 for further discussion._
