### ISSUE TITLE
Small issue with Redmine 3.4

### ISSUE THREAD

**Issue by Atmis** [paginagmbh/redmine_lightbox2#38]
Hello,

I noticed a small defect with Redmine 3.4 which introduced a change in the file preview (http://www.redmine.org/issues/25988)

In the history messages :
<img width="236" alt="screenshot 2017-07-10 23_54_04 pma" src="https://user-images.githubusercontent.com/5329747/28041817-1c54f02a-65cb-11e7-9789-883d820f451a.png">

If you click on the file link, you get an error message :
<img width="266" alt="screenshot 2017-07-10 23_55_42 pma" src="https://user-images.githubusercontent.com/5329747/28041884-50a78acc-65cb-11e7-9153-29c73cf29218.png">

But if you click on the thumbnail, then the picture shows normally.

Thanks again for this great plugin

**Comment by tofi86** [comment]
Thanks, I will take a look in the next few days...

**Comment by tofi86** [comment]
Thanks for reporting this. I pushed a couple of changes and fixes to the `master` branch but didn't release the new version 0.4.0 officially yet as I'm waiting for another fix with #37 

The attachment list now looks like this in 3.4:

![bildschirmfoto 2017-07-28 um 16 28 05](https://user-images.githubusercontent.com/365118/28721881-06f91dec-73b2-11e7-960a-f1da9116ac3f.png)

The journal details like this:

![bildschirmfoto 2017-07-28 um 16 28 26](https://user-images.githubusercontent.com/365118/28721892-0d10cf40-73b2-11e7-8f4b-c7d7337d358c.png)


----

Stay tuned for official release of version 0.4.0 soon!

**Comment by tofi86** [comment]
Screw it, not waiting for the other issue as I think it's not my fault anyway... ;-)

Version 0.4.0 for Redmine 3.4 has officially been released now... 🎉

**Comment by Atmis** [comment]
Thanks a lot !
After a quick test, I confirm it works as expected :-)

**Comment by tofi86** [comment]
Thanks! 👍
