### ISSUE TITLE
PDF not working

### ISSUE THREAD

**Issue by The-Judge** [paginagmbh/redmine_lightbox2#4]
Hi there - are there any requirements to be fulfilled for PDF preview? It works fine for Images. PDF do not have a thumbnail, but an Eye-Symbol next to it's filename:

![unbenanntes bild](https://cloud.githubusercontent.com/assets/904987/5391869/75d4692e-8120-11e4-8fe2-98f54f0a4ca9.png)

When clicking on the Eye Symbol, the PDF gets downloaded and an empty (white) Lightbox is shown. When the sliders are clicked, the files are downloaded again.

I have made a screencast of this: http://youtu.be/ZTFqUb2X4H0

**Comment by pyroit** [comment]
Hi,
i have the same Issue here.
Did you found a solution? I tried to tell firefox to open pdf's in the browser, but still the same behavior.
Thank you

**Comment by The-Judge** [comment]
No. I did not find a solution with suggested hints, also. Other webapps do work properly with the same browsers and file types.

**Comment by tofi86** [comment]
Alright, will digg deeper into the issue in the next couple of weeks.
The "open pdf inline" functionality was provided by original plugin author not by me. So will take some time for me to figure this out.

File: https://github.com/paginagmbh/redmine_lightbox2/blob/master/app/controllers/attachments_controller.rb
Code: ```:disposition => 'inline'```

Don't know of another rails method to send pdf's to inline view at the moment...

**Comment by shuozhifenxi** [comment]
Maybe this is helpful? 

https://github.com/mozilla/pdf.js/

**Comment by shuozhifenxi** [comment]
This is a pure-javascript library that uses HTML5 functions to open a PDF file and render it in the page.

**Comment by tofi86** [comment]
alright, this should be fixed with latest release v0.1.0

`:disposition => 'inline'` wasn't sent because controller wasn't loaded (bug from initial plugin author).
Fixed this behaviour for redmine 2.x

**Comment by jeanfor** [comment]
I have installed the update. It works fine if you have only one pdf. If you put 2 or more pdf's when opening a pdf and trying to browse through the pdf instead it goes to the next pdf

**Comment by tofi86** [comment]
Which browser do you use? How do you try to browse through the PDF? Keyboard? Mouse wheel?

**Comment by jeanfor** [comment]
Chrome, I use the slider on the side

**Comment by tofi86** [comment]
@jeanfor: confirmed this issue. see ticket #5

**Comment by jeanfor** [comment]
Thanks for fixing

**Comment by The-Judge** [comment]
Just tested and it works very well (commit 84cca94648e6cf103f276c025c1e7087e6fd7a01). When there are multiple multi-page PDF files attached, the PDF is scrollable over multiple pages. The lightbox-arrows switch to the next attachment:

![unbenanntes bild2](https://cloud.githubusercontent.com/assets/904987/5797308/b3b9ae4c-9fb7-11e4-8761-300080058264.png)

I'm using Chrome in Windows 7.

@tofi86 Thanks a lot for fixing! :)

**Comment by shuozhifenxi** [comment]
Thank you very much for fixing the bug.

**Comment by pyroit** [comment]
Also a huge thank you from my side
