### ISSUE TITLE
DMSF thumbnails support

### ISSUE THREAD

**Issue by dinya** [paginagmbh/redmine_lightbox2#40]
Thanks a lot for amazing plugin!

The question

1. Thumbnail with internal redmine macros

```
{{thumbnail(fig.png, size=300)}}
```

2. Thumbnail with [DMSF macros](https://github.com/danmunn/redmine_dmsf)

```
{{dmsftn(777, size=300)}}
```

The first works well with redmine_lightbox2 (I use v0.3.2) --- the figure is opened in the current tab as window. The second doesn't work --- it's opened in the new tab like without redmine_lightbox2. 

Is it possible to add DMSF thumbnails support?

**Comment by tofi86** [comment]
This should be doable. I will try to have a look in the next couple of days...

**Comment by tofi86** [comment]
Note: In Redmine 3.4 the DMFS plugin seems to have a bug with the `size` parameter: https://github.com/danmunn/redmine_dmsf/issues/746 It does not get evaluated.

**Comment by tofi86** [comment]
Alright, this has been resolved with new version 0.4.1 for Redmine 3.4

**Comment by tofi86** [comment]
This has been backported to Redmine 3.3 branch and made available as version 0.3.4 for Redmine 3.3

**Comment by dinya** [comment]
Thanks for the work done!

But v0.3.4 doesn't work with ``{{dmsftn}}` `under  Redmine 3.3.1 + DMSF 1.5.9 (from master) + Ruby 2.3.3-p222 (Ubuntu 16.04 x64): the figure is opened in the new tab like in the original Redmine.

**Comment by tofi86** [comment]
Unfortunately I don't have a Redmine 3.3 around here for testing. I could set up a dev installation but that would take a while.

Can you please copy the HTML `a` element including `img` child element of the thumbnail?

And then please disable the lightbox plugin and copy the same, original element once again. This is the original element and I have to see what I have to modify.

**Comment by dinya** [comment]
> Can you please copy the HTML ``a`` element including ``img`` child element of the thumbnail and insert here?
>
>And then please disable the lightbox plugin and copy the same, original element once again and insert here. This is the original element and I have to see what I have to modify.

**With** redmine_lightbox2 v0.3.4

```html
<a target="_blank" title="" data-downloadurl="image/png:TEST_IMAGE.png:/dmsf/files/351/view" href="/dmsf/files/351/view"><img alt="TEST_IMAGE" width="auto" height="200" src="/dmsf/files/351/view" /></a>
```

**Without** redmine_lightbox2 v0.3.4 (``redmine_lightbox2`` was deleted with ``bundle exec rake redmine:plugins:migrate NAME=redmine_lightbox2 VERSION=0 RAILS_ENV=production`` and plugin directory was removed from ``plugins``)

```html
<a target="_blank" title="" data-downloadurl="image/png:TEST_IMAGE.png:/dmsf/files/351/view" href="/dmsf/files/351/view"><img alt="TEST_IMAGE" width="auto" height="200" src="/dmsf/files/351/view" /></a>
```

**Comment by tofi86** [comment]
Thanks! Indeed they look the same, but with the lightbox it should look different...

Which browser do you use?

Where did you use the thumbnail macro? On a wiki page or in an issue description/comment? Or somewhere else?

Can you reinstall the plugin and make sure you run the plugin migration? And also make sure to clear the browser cache for your redmine site after that so that JavaScript files get a fresh reload...

**Comment by dinya** [comment]
> And also make sure to clear the browser cache for your redmine site after that so that JavaScript files get a fresh reload...

This helped. Thanks!

btw, ``{{dmsf_image(8)}}`` macros inserts image too. Do you add it's support?

**Comment by dinya** [comment]
... and description from dmsf file

**Comment by tofi86** [comment]
> This helped. Thanks!

Great! Glad it works now! :-)

**Comment by tofi86** [comment]
> btw, {{dmsf_image(8)}} macros inserts image too. Will you add it's support?

I had a look at this as well, but it does not generate a Thumbnail Link (a element) which I could use as an anchor for the lightbox. So no, this will not be supported.

**Comment by tofi86** [comment]
> ... and description from dmsf file.
> 
> I mean adding the result of {{dmsfdesc(351)}} to the file name in the figure subscription (like for ordinary attachments)

This is not doable because the description does not exist in the html code when {{dmsftn()}} macro was executed. I only add lightbox effect with javascript when page is loaded but in that stage I cannot pull the description with a macro anymore. Sorry.

**Comment by dinya** [comment]
I have ``filename.doc`` (ms office) file with id 100 in DMSF. I linked to the file  with ``{{dmsf(100)}}`` on the wiki page.

When I click to corresdoning link the ``redmine_lightbox2`` tries to render the dmsf document and shows popup window titled with ``filename.doc``:

```
The requested content cannot be loaded.
Please try again later.
```

**Comment by tofi86** [comment]
Thanks for reporting this. I will try to have a look this week...

**Comment by tofi86** [comment]
I pushed a fix to the `master` branch for Redmine 3.4 and to the `redmine-3.3` branch for Redmine 3.3

Can you please test it? It should work.

`doc` documents will not show in a lightbox, other documents will not as well, but PDF documents inserted with `{{dmsf(100)}}` will show in a preview lightbox.

Is this okay? If so, please tell me and I will release a new version in the next couple of days...

**Comment by dinya** [comment]
Unfortunately without any changes.

May be I made a mistake while update? I use redmine 3.3 and I made

```bash
git fetch
git checkout redmine-3.3
bundle exec rake redmine:plugins:migrate RAILS_ENV=production 
```

What I noted. After saving the text with ``{{dmsf(100)}}`` (docx) the plugin works: download -- not preview. But if I reload the page the plugin tries to show the preview window again

**Comment by tofi86** [comment]
I assume you have already cloned the repository and checked out the branch `redmine-3.3`. In that case you only fetched the changes, but did not pull them:

```
git fetch
git checkout redmine-3.3
git pull
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

Try again and reload the page without cache (clear browser cache first or e.g. with Firefox use Ctrl+Shift+R).

**Comment by dinya** [comment]
@tofi86 

It's ok now. Thanks!

**Comment by tofi86** [comment]
Perfect! Glad it works! Enjoy!

**Comment by dinya** [comment]
@tofi86 

*.bmp files are not avalible in preview.

**Comment by tofi86** [comment]
As far as I know, bmp is also not supported as thumbnail in Redmine. The plugin never supported bmp files for preview, only JPG, JPEG, PNG, GIF.

**Comment by dinya** [comment]
Dear @tofi86,

Redmine DMSF 1.6.x allows documents attachements to issue.

Is it doable to add preview thumbnails of DMS section with preview lightbox?

# Current variant

![current](https://user-images.githubusercontent.com/2182222/38980692-f32d85f0-43d6-11e8-84cc-cce280905bc0.png)

<details><summary>Attachments section</summary>
<p>

```html
<div class="attachments">
<div class="contextual">
  <a title="Edit attached files" class="icon-only icon-edit" href="/attachments/issues/562/edit">Edit attached files</a>
</div>
<table>
<tbody><tr>
  <td>
      <a class="icon icon-attachment lightbox_preview" href="/attachments/download/820/test_image0.jpg">test_image0.jpg</a>      </td>
      <td class="alignrigth">
      <a class="icon-only icon-magnifier lightbox_preview jpg" rel="attachments" title="test_image0.jpg" href="/attachments/download/820/test_image0.jpg">View</a>

    <a class="icon-only icon-download" title="Download" href="/attachments/download/820/test_image0.jpg">test_image0.jpg</a>  </td>
  <td class="alignrigth">
    <span class="size">763 KB</span>
  </td>
  <td></td>
  <td>
      <span class="author">Redmine Admin, 04/19/2018 12:16 PM</span>
  </td>
  <td>
      <a data-confirm="Are you sure?" class="delete icon-only icon-del" title="Delete" rel="nofollow" data-method="delete" href="/attachments/820">Delete</a>
  </td>
</tr>
</tbody></table>
	  <div class="images">
	      <a class="lightbox" rel="thumbnails" title="test_image0.jpg" href="/attachments/download/820/test_image0.jpg"><img src="/attachments/download/820/test_image0.jpg" alt="Test image0" width="180"></a>
	  </div>
</div>
```
</p>
</details>

<details><summary>DMS section</summary>
<p>

```html
<div class="attachments dmsf_parent_container">
          <p>
  <a class="thumbnail" title="test_image1.jpg" href="/dmsf/files/1329/view" data-fancybox-type="image">test image1</a>
      <a class="icon-only icon-magnifier" title="View" href="/dmsf/files/1329/view">View</a>
  
  <span class="size">(760 KB)</span>
  <span class="author">Redmine Admin, 04/19/2018 12:17 PM</span>
  <span class="dmsf_upload_select">
      <a title="test image1 details" class="icon-only icon-edit" href="/dmsf/files/1329"></a>
    <a title="Send documents by email" class="icon-only icon-email-disabled" rel="nofollow" data-method="post" href="/projects/5/dmsf/entries?email_entries=email&amp;files%5B%5D=1329"></a>
      <a title="Lock to prevent changes for other members" class="icon-only icon-lock" href="/dmsf/files/1329/lock"></a>
        <a title="Notifications not active: Activate" class="icon-only icon-email-add" href="/dmsf/files/1329/notify/activate"></a>
        <a data-confirm="Are you sure?" title="Delete" class="icon-only icon-del" rel="nofollow" data-method="delete" href="/dmsf/files/1329?commit=yes"></a>
    
            <span class="icon-only"></span>

  </span>
</p>

          <p>
  <a target="_blank" class="icon icon-file filetype-docx dmsf-icon-file" title="" data-downloadurl="application/vnd.openxmlformats-officedocument.wordprocessingml.document:test ms word document.docx:/dmsf/files/1330/view" href="/dmsf/files/1330/view">test ms word document</a>
  
  <span class="size">(24.1 KB)</span>
  <span class="author">Redmine Admin, 04/19/2018 12:38 PM</span>
  <span class="dmsf_upload_select">
      <a title="test ms word document details" class="icon-only icon-edit" href="/dmsf/files/1330"></a>
    <a title="Send documents by email" class="icon-only icon-email-disabled" rel="nofollow" data-method="post" href="/projects/5/dmsf/entries?email_entries=email&amp;files%5B%5D=1330"></a>
      <a title="Lock to prevent changes for other members" class="icon-only icon-lock" href="/dmsf/files/1330/lock"></a>
        <a title="Notifications not active: Activate" class="icon-only icon-email-add" href="/dmsf/files/1330/notify/activate"></a>
        <a data-confirm="Are you sure?" title="Delete" class="icon-only icon-del" rel="nofollow" data-method="delete" href="/dmsf/files/1330?commit=yes"></a>
    
            <span class="icon-only"></span>

  </span>
</p>

    

  </div>
```
</p>
</details>

# Want

![want](https://user-images.githubusercontent.com/2182222/38980711-008551d8-43d7-11e8-94c7-79912a708ac1.png)

<details><summary>DMS section like this</summary>
<p>

```html
<div class="attachments dmsf_parent_container">
          <p>
  <a class="thumbnail" title="test_image1.jpg" href="/dmsf/files/1329/view" data-fancybox-type="image">test image1</a>
      <a class="icon-only icon-magnifier" title="View" href="/dmsf/files/1329/view">View</a>
  
  <span class="size">(760 KB)</span>
  <span class="author">Redmine Admin, 04/19/2018 12:17 PM</span>
  <span class="dmsf_upload_select">
      <a title="test image1 details" class="icon-only icon-edit" href="/dmsf/files/1329"></a>
    <a title="Send documents by email" class="icon-only icon-email-disabled" rel="nofollow" data-method="post" href="/projects/5/dmsf/entries?email_entries=email&amp;files%5B%5D=1329"></a>
      <a title="Lock to prevent changes for other members" class="icon-only icon-lock" href="/dmsf/files/1329/lock"></a>
        <a title="Notifications not active: Activate" class="icon-only icon-email-add" href="/dmsf/files/1329/notify/activate"></a>
        <a data-confirm="Are you sure?" title="Delete" class="icon-only icon-del" rel="nofollow" data-method="delete" href="/dmsf/files/1329?commit=yes"></a>
    
            <span class="icon-only"></span>

  </span>
</p>

          <p>
  <a target="_blank" class="icon icon-file filetype-docx dmsf-icon-file" title="" data-downloadurl="application/vnd.openxmlformats-officedocument.wordprocessingml.document:test ms word document.docx:/dmsf/files/1330/view" href="/dmsf/files/1330/view">test ms word document</a>
  
  <span class="size">(24.1 KB)</span>
  <span class="author">Redmine Admin, 04/19/2018 12:38 PM</span>
  <span class="dmsf_upload_select">
      <a title="test ms word document details" class="icon-only icon-edit" href="/dmsf/files/1330"></a>
    <a title="Send documents by email" class="icon-only icon-email-disabled" rel="nofollow" data-method="post" href="/projects/5/dmsf/entries?email_entries=email&amp;files%5B%5D=1330"></a>
      <a title="Lock to prevent changes for other members" class="icon-only icon-lock" href="/dmsf/files/1330/lock"></a>
        <a title="Notifications not active: Activate" class="icon-only icon-email-add" href="/dmsf/files/1330/notify/activate"></a>
        <a data-confirm="Are you sure?" title="Delete" class="icon-only icon-del" rel="nofollow" data-method="delete" href="/dmsf/files/1330?commit=yes"></a>
    
            <span class="icon-only"></span>

  </span>
</p>

	  <div class="images">
	      <a class="lightbox" rel="thumbnails" title="test_image1.jpg" href="/dmsf/files/1329/view"><img src="/dmsf/files/1329/view" alt="test image1" width="180"></a>
	  </div>    

  </div>
```

</p>
</details>

# My environment

<details><summary>My environment</summary>
<p>

```
Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
...
  redmine_dmsf                   1.6.1
...
  redmine_lightbox2              0.4.3
...
```

</p>
</details>

**Comment by tofi86** [comment]
The dmsf project needs to fix severe bug https://github.com/danmunn/redmine_dmsf/issues/845 first before I can do this.

Anyways, how is it possible to attach dmsf files to an issue? Haven't found a solution (but also couldn't access projects settings due to bug mentioned above).

**Comment by dinya** [comment]
> Anyways, how is it possible to attach dmsf files to an issue? Haven't found a solution (but also couldn't access projects settings due to bug mentioned above).

Look at ``redmine_dmsf`` plugin settings in Administration. According to changelog this feature since 1.6.0. It's look like checkbox named smth like "Attach*issue*" (sorry, haven't Redmine with dmsf v1.6.x onboard near at hand).

**Comment by tofi86** [comment]
found it, thanks!  "act as attachable"

**Comment by tofi86** [comment]
added a separate issue for this request => #53

@dinya please always open a new issue for requests in the future...

**Comment by dinya** [comment]
@tofi86 

> please always open a new issue for requests in the future...

Okay. Pardon, I just thought the request is in this issue context.
