### ISSUE TITLE
Conflic with plugin redmine_agile on Chrome 59&60

### ISSUE THREAD

**Issue by daronz** [paginagmbh/redmine_lightbox2#41]
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x64-mingw32]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.4
  redmine_lightbox2              0.4.1

redmine_agile: https://www.redmineup.com/pages/plugins/agile
Testing on Google Chrome 59.0.3071.115 and 60.0.3112.90, but no problem with IE11 and Microsoft Edge.

Click "New Issue" and you will find the scroll bar missing.
![screenshot1](https://user-images.githubusercontent.com/12730642/29055559-b508d604-7c2f-11e7-8828-0e6b00822851.png)

Then if you click the "Help" button, the scroll bar will appears again.
![screenshot2](https://user-images.githubusercontent.com/12730642/29055560-b5270084-7c2f-11e7-8021-2aad7637435b.png)

**Comment by tofi86** [comment]
Thanks for reporting but this has already been reported in #37. Closing this as duplicate.

This is not a problem with the lightbox plugin, but is related to a code change made by the redmine_agile folks. Here's a workaround you can implement until they will release a new version: https://github.com/paginagmbh/redmine_lightbox2/issues/37#issuecomment-318714797

Hope this helps!
