### ISSUE TITLE
Assets are not loaded

### ISSUE THREAD

**Issue by manuscle** [paginagmbh/redmine_lightbox2#42]
Hi, after installing the plugin and restarted redmine, the assets files cannot be accessed.
The plugin appear in the activated plugins list in the configuration page
![2017-08-08 16_29_11-informations - support marchal bodin](https://user-images.githubusercontent.com/596562/29076794-d2094ff0-7c56-11e7-94f1-4af813d7e4e4.png)
![2017-08-08 16_31_41-perso - sage - support marchal bodin](https://user-images.githubusercontent.com/596562/29076914-29e39384-7c57-11e7-95f6-be7fc6a51880.png)

**Comment by tofi86** [comment]
Did you follow the installation instructions to the point?

Did you run `rake redmine:plugins:migrate RAILS_ENV=production` from redmine root dir?

Can you make sure that after running this and restarting redmine, the assets are physically located in `${redmine_root}/public/plugin_assets/redmine_lightbox2/` and have the correct permissions to be accessible by your webserver?

**Comment by manuscle** [comment]
Yes, i did it and restarted redmine

```
www-data@web01:~/redmine/plugins/redmine_lightbox/assets$ cd ~/redmine/
www-data@web01:~/redmine$ rake redmine:plugins:migrate RAILS_ENV=production
Migrating redmine_lightbox2 (Redmine Lightbox 2)...
www-data@web01:~/redmine$ ll plugins/redmine_lightbox/assets/*
plugins/redmine_lightbox/assets/images:
total 44
-rw-r--r-- 1 www-data www-data    43 août   6 17:10 blank.gif
-rw-r--r-- 1 www-data www-data 13984 août   6 17:10 fancybox_loading@2x.gif
-rw-r--r-- 1 www-data www-data  6567 août   6 17:10 fancybox_loading.gif
-rw-r--r-- 1 www-data www-data  1003 août   6 17:10 fancybox_overlay.png
-rw-r--r-- 1 www-data www-data  6553 août   6 17:10 fancybox_sprite@2x.png
-rw-r--r-- 1 www-data www-data  1362 août   6 17:10 fancybox_sprite.png

plugins/redmine_lightbox/assets/javascripts:
total 28
-rw-r--r-- 1 www-data www-data 23135 août   6 17:10 jquery.fancybox-2.1.5.pack.js
-rw-r--r-- 1 www-data www-data  2532 août   6 17:10 lightbox.js

plugins/redmine_lightbox/assets/stylesheets:
total 12
-rw-r--r-- 1 www-data www-data 4955 août   6 17:10 jquery.fancybox-2.1.5.css
-rw-r--r-- 1 www-data www-data  717 août   6 17:10 lightbox.css
www-data@web01:~/redmine$ sudo service apache2 restart
[ ok ] Restarting web server: apache2 ... waiting .

```

**Comment by tofi86** [comment]
This is the wrong folder!

I said you have to make sure that the assets are loaded in THIS folder: `${redmine_root}/public/plugin_assets/redmine_lightbox2/`
This is NOT the `plugins` folder, it's the `public` folder! This is where the plugin migration copies the assets to make them available to the public webfrontend.

Also I noted that your plugin is located in the wrong folder:

> `www-data@web01:~/redmine/plugins/redmine_lightbox/assets$ cd ~/redmine/`


Please read the README once again to the point. There is written:

> Clone or download this repo into your redmine_root/plugins/ folder
```
$ git clone https://github.com/paginagmbh/redmine_lightbox2.git
```
> If you downloaded a tarball / zip from master branch, make sure you rename the extracted folder to `redmine_lightbox2`

But you downloaded, copied or cloned the plugin to a folder named `redmine_lightbox` - so this can never work!

**Comment by tofi86** [comment]
If you rename this folder `~/redmine/plugins/redmine_lightbox` to `~/redmine/plugins/redmine_lightbox2` and run the migration again, everything should be working fine!

**Comment by manuscle** [comment]
Oh yes i made a mistake while renaming the plugin folder!
I could not clone the repos because my redmine version is too old for the latest plugin version.
So i manually downloaded the corresponding version but renamed redmine_lightbox instead of redmine_lightbox2.
I correctly renamed the folder and everything working fine now
My apologize for this stupid error and thanks for your help!

**Comment by tofi86** [comment]
No problem. You're welcome!

You could also have cloned the repo and then checked out the branch for Redmine 3.3 like so:

```
cd ~/redmine/plugins/
git clone https://github.com/paginagmbh/redmine_lightbox2.git
cd redmine_lightbox2
git checkout redmine-3.3
cd ../../
rake redmine:plugins:migrate RAILS_ENV=production
```

**Comment by manuscle** [comment]
It's a better idea, I'll do that. Thank for the trick!
