### ISSUE TITLE
When close lightbox scrollbar will hide

### ISSUE THREAD

**Issue by brydio** [paginagmbh/redmine_lightbox2#44]
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.4.1-p111 (2017-03-22) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  redmine_agile                  1.4.4
  redmine_checklists             3.1.6
  redmine_issue_dynamic_edit     0.4.0
  redmine_lightbox2              0.4.3
  redmine_webhook                0.0.2

**Comment by tofi86** [comment]
This is most likely caused by a bug in the redmine_agile plugin (see #37 and https://github.com/paginagmbh/redmine_lightbox2/issues/37#issuecomment-318714797 for a workaround), although I cannot really indentify what your problem is because the title of the issue doesn't make sense.
