### ISSUE TITLE
No preview icon for swf files

### ISSUE THREAD

**Issue by e-evdokimov** [paginagmbh/redmine_lightbox2#45]
There are no preview icon for swf files in the latest version of the plugin:

![no_preview_icon_4swf](https://user-images.githubusercontent.com/12083189/29811195-4f54112a-8cab-11e7-8143-ee81c4e68630.PNG).

Are there any other ways to preview swf attachments?

**Comment by tofi86** [comment]
Indeed, SWF support has been dropped in the latest version. Didn't thought someone is using this... Sorry! 😳 
Is this a requirement for you?

**Comment by e-evdokimov** [comment]
Thank you for your answer.
Not that it was very necessary, just noticed some UI changes and inconsistency with the description of the plugin. )

**Comment by tofi86** [comment]
Closing this issue as preview support for Shockwave Flash / Adobe Flash files was never a big feature...
