### ISSUE TITLE
Scrollbar in Chrome(ium) disappear if v0.4.3 is enabled 

### ISSUE THREAD

**Issue by imolein** [paginagmbh/redmine_lightbox2#46]
Hi,

I enabled lightbox2 v0.4.3 in our redmine 3.4 installation and after that the scrollbar disappears in issues. This only happens in Chrome/Chromium, not in Firefox.

Systeminformation:
```
Environment:
  Redmine version                3.4.2.stable
  Ruby version                   2.3.0-p0 (2015-12-25) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
```

**Comment by tofi86** [comment]
This is caused by a bug in the redmine_agile plugin (see #37).

**Comment by imolein** [comment]
Thanks for the fast answer! :)
