### ISSUE TITLE
Cannot view images in the browser in Redmine 3.4.x

### ISSUE THREAD

**Issue by andrei-mihaila** [paginagmbh/redmine_lightbox2#47]
Hi,

There are some issues with viewing attachment images in the browser in Redmine 3.3.x - the images are always downloaded. They fixed the issue in 3.4.2 as they said in [this ticket](http://www.redmine.org/issues/25282).

I think the `links` template in this plugin needs to be updated to allow viewing the images in the browser again. I [tried it in my fork](https://github.com/andrei-mihaila/redmine_lightbox2/commit/1bc76ed60de17e2577f943468d1bf92ae178fcbc). If you think the solution is ok please let me know and I'll do a pull request.

Cheers,
Andrei

**Comment by tofi86** [comment]
I wasn't able to reproduce the problem. Viewing image attachments works fine with current versions of my plugin in Redmine 3.3.x as well as in Redmine 3.4.2 and current trunk.

Also, your changes break the PDF preview/lightbox functionality.

**Comment by andrei-mihaila** [comment]
Hi, @tofi86,

Sorry, I didn't explain it properly, my bad!

Your plugin does work fine with both branches - it shows the images in the issue page using a lightbox pop-up. The problem is with trying to view the raw images in the browser without using the lightbox pop-up.

It used to work by opening the image link in a new tab (easy to do in Chrome by middle-clicking, for example). It stopped working because the Redmine team changed [the controller](https://github.com/redmine/redmine/blob/master/app/controllers/attachments_controller.rb#L235) to always offer a file to download (`disposition: attachment`) not one to display inline. So opening the link to the image in a new tab just downloads it and then the image must be viewed in an external application (which is cumbersome, for me at least).

As I understand from [this ticket](http://www.redmine.org/issues/25282#note-5) they changed the behaviour in Redmine 3.4.0 to do file preview by default (this time it is a preview in a dedicated page, not the raw file). So I was thinking that this behaviour should be reflected in your plugin. It would mean offering the exact core Redmine experience plus the view in a lightbox pop-up and download buttons.

Thank you,
Andrei

**Comment by tofi86** [comment]
Sorry for the late reply.

But Redmine 3.4 offers the download icon and the latest version of my plugin does not change this functionality:

![bildschirmfoto 2018-01-02 um 23 48 47](https://user-images.githubusercontent.com/365118/34503241-9654a74a-f017-11e7-9afd-d6ecefe1bde3.png)

* Clicking the filename will open a popup
** replacing the default redmine behaviour of opening a "download/preview" page
* Clicking the magnifier icon will open a popup
** my plugin adds this icon for convenience
* Clicking the download icon downloads the image
** From a quick check I think I didn't change this functionality...

What else should the lightbox plugin do?

If you wish additional functionality, please send me a PullRequest without removing or breaking existing functionality.

**Comment by tofi86** [comment]
Closing this issue as stale. No response by the original author.
