### ISSUE TITLE
DMSF preview

### ISSUE THREAD

**Issue by Rodrigosalasv** [paginagmbh/redmine_lightbox2#48]
Hello,

I'm using 0.3.5 version of Lightbox 2 plugin.
What is the interaction with DMSF plugin?
I don't see anything

**Comment by tofi86** [comment]
If you insert DMSF links or thumbnails in a wiki page, you can click on them and see the big image in a lightbox.

**Comment by tofi86** [comment]
Closing this as it seems as the question was answered. Feel free to reopen if necessary.
