### ISSUE TITLE
PDF Preview not working with Redmine 3.4.3

### ISSUE THREAD

**Issue by Winslow-AT** [paginagmbh/redmine_lightbox2#50]
Hello,

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2

redmine_lightbox2              0.4.3

Preview of images works, PDF just brings a blank popup. This did work with redmine 3.4.2 but since the last update it's broken.

Thanks in advance

**Comment by tofi86** [comment]
Thanks for your report.
However, I cannot reproduce the problem. It works well for me in Firefox 57 and Chrome 63 with Redmine 3.4.3 and Plugin 0.4.3

On which page are you experiencing this problem? On an Issue page? Or an a Wiki page?

Where did you click on the PDF link? In the attachment section of an Issue / Wiki page? Or in an Issue Journal entry?

**Comment by Winslow-AT** [comment]
Thanks for testing. After checking everything again, the reason for the blank page was actually the browser blocking it because of X-Frame-Options: Deny.

After setting the header to Sameorigin everything works again. Before the redmine and plugin upgrade this wasn't needed. I'm fine with setting the header this way, just didn't think about it before/after upgrading.

Thanks for the help.
