### ISSUE TITLE
Support for DMSF 1.6 feature "DMSF files act as attachable on issues"

### ISSUE THREAD

**Issue by tofi86** [paginagmbh/redmine_lightbox2#53]
@dinya request in https://github.com/paginagmbh/redmine_lightbox2/issues/40#issuecomment-382665116:

> Redmine DMSF 1.6.x allows documents attachements to issue.
>
> Is it doable to add preview thumbnails of DMS section with preview lightbox?

**Comment by tofi86** [comment]
I will add support for this feature in `master` branch for Redmine 3.4.

Is Redmine 3.3 support also requested?

**Comment by tofi86** [comment]
@dinya: please test the current master branch with Redmine 3.4 and tell me whether it works as expected.

my tests have been successfull and I also added `rel` attribute so you can have a slideshow of all dmsf thumbnails (use arrow keys or icons beside the lightbox image).

**Comment by dinya** [comment]
@tofi86 

Lightbox is works well, but:

1. There are no thumbnails after titles like for "classic" attachments. (BTW, maybe add option in settings to either show or not thumbnails both in attachments and in DMS content.)

![no_thumbnails](https://user-images.githubusercontent.com/2182222/39129394-d1a43a00-4723-11e8-9713-1875ba952511.png)

2. DMS title's are not shown in lightbox:

![caption from dms](https://user-images.githubusercontent.com/2182222/39129384-c9bf1ff8-4723-11e8-933a-f4d7f096b369.png)

**Comment by dinya** [comment]
Dear @tofi86 

Do you have any ideas?

**Comment by tofi86** [comment]
@dinya sorry, I'm currently on parental leave with a newborn and not checking open source projects regularly.

In my case, thumbnails are shown, probably because I enabled thumbnail generation in redmine settings?
I can try to add thumbnails even if this feature is turned off, like I do with the normal image attachments. will see...

About the description: you're right. I will try to take a look soon.

**Comment by dinya** [comment]
@tofi86 

> I'm currently on parental leave with a newborn

My sincere congratulations! :-)

>In my case, thumbnails are shown, probably because I enabled thumbnail generation in redmine settings?

You are right: I'm enable this and it works as expected (I never used this feature before).

**Comment by tofi86** [comment]
Thanks! 😊 

Glad it works for you! Nevertheless, I will try to find a solution similar to the image attachements.

**Comment by tofi86** [comment]
Fixed with 8e8dc02 for Redmine 3.4.

![Bildschirmfoto 2019-11-02 um 19 46 55](https://user-images.githubusercontent.com/365118/68075577-de286380-fda9-11e9-8b9b-4923ad8f54d3.png)

Redmine 4 support will be available once the Redmine 3 compatible version has been released and merged to the Redmine 4 compatible version.

**Comment by tofi86** [comment]
Redmine 4 support on `master` was added.
