### ISSUE TITLE
How to use/test the plugin?

### ISSUE THREAD

**Issue by Starbase12** [paginagmbh/redmine_lightbox2#58]
Hi,

we're using Bitnami Redmine in an Win-Environment and I followed your Install-Guide. The Installation seems to be successfull, because after restarting all Redmine-Services, your Plugin is showed under Administration -> Plugins.

As you can see in the attached Images, I tried it with "!nametothepdf.pdf! but after clicking "preview" or "save" there is no preview. With JPGs etc. it's working fine. Maybe you can tell me how to use your Plugin correctly.

Redmine 3.4.2.stable is installed.

Thanks in advanced.

![redmine-plugins](https://user-images.githubusercontent.com/18394355/43631587-e132c8bc-9703-11e8-9cd4-c7339e70e4b2.png)

![no-preview](https://user-images.githubusercontent.com/18394355/43631585-e1001ca0-9703-11e8-8559-23d83135e237.png)

**Comment by tofi86** [comment]
If you insert an image like this it's not inserted as thumbnail and therefore there is no preview for it.

Use the thumbnail macro to create thumbnails which can be previewed.

The plugin also works if you add image attachments to issues.

**Comment by Starbase12** [comment]
thanks for your answer tofi86. We're Beginners using redmine. Can you tell me how to use "Thumbnail macro" to create Thumbnails and how I can insert them in the wiki, so that a Thumbnail from a pdf is showed in the wiki?

**Comment by tofi86** [comment]
As far as I know, Redmine cannot create thumbnails from PDF. There may be plugins for that however.

In this case you can only use it with images like this:

```
{{thumbnail(image.png)}}
{{thumbnail(image.png, size=300, title=Thumbnail)}}
```

from the redmine help:
`http(s)://${your-redmine-instance.com}/help/en/wiki_syntax_detailed_textile.html`

This plugin supports preview for PDF's only from links (e.g. the attachment list at the bottom in a wiki page).

**Comment by tofi86** [comment]
I'm closing this issue. Feel free to reopen or comment if needed.
