### ISSUE TITLE
Firefox 63 - doesn't work anymore

### ISSUE THREAD

**Issue by mdz0r** [paginagmbh/redmine_lightbox2#61]
Hello,

FF update last night. Lightbox2 doesn't work anymore :(

ctrl+v doesn't do anything

![image](https://user-images.githubusercontent.com/42241744/47553653-e7196600-d907-11e8-8bf7-7ca2e546da61.png)

**Comment by tofi86** [comment]
YOu obviously reported this issue to the wrong repository. As you can see in the screenshot, the error is thrown by the clipboard image paste plugin and you also mention ctrl+v to copy an image. This plugin (lightbox 2 ) does not support keyboard shortcuts nor has any links to the clipboard plugin.

**Comment by mdz0r** [comment]
Indeed wrong redmine plugin, my bad, sorry!
