### ISSUE TITLE
Slide preview in DMSF folder

### ISSUE THREAD

**Issue by dinya** [paginagmbh/redmine_lightbox2#64]
Hello @tofi86 

When we are on the issue page containing DMS objects the lightbox2 allows to preview objects in slide mode (Previous/Next buttons are availiable in Preview mode).

It will be very cool if the lightbox2 will allow to preview images from DMSF folder page.

![dmsf_folder](https://user-images.githubusercontent.com/2182222/56941086-7c9de880-6b2b-11e9-940c-35d4a8a21b74.png)

**Comment by tofi86** [comment]
Added and tested for Redmine 3.4 on branch `redmine-3.4`.

Added and tested for Redmine 4.0 on branch `master`.

No new version has been released yet.

@dinya Could you please test the latest version from master branch in Redmine 4? Is this what you expected?

Unfortunately I couldn't get it working for PDF previews, although it works for PDF previews in wiki pages. I have no idea what's wrong. So for the moment I'll skip PDF preview in the DMS browser page.

**Comment by dinya** [comment]
@tofi86 

Good job! 👍 Thanks a lot.

I tested the plugin with redmine-3.4. But I have plans for migration to redmine-4 soon. And redmine_lightbox2 will be tested at the same time.

**Comment by tofi86** [comment]
Perfect, thanks! Closing this as solved :-)

**Comment by dinya** [comment]
@tofi86 

Could you add dmsf file ID to image label (something like ``[<id>] <title>``)?

Use case. I found the image of interest in the slide preview and wanna link to it in some issue or wiki page with ``{{dmsftn(id)}}``.

Currently I should remember the title (label), close preview and find ID by title in the files list. And then I can add the link. But the ID presence  in the label in the bottom  prevents this three unnecessary steps (remember, close and find).

What do you think?

**Comment by tofi86** [comment]
> What do you think?

See #73
