### ISSUE TITLE
Syntax error in Internet Explorer 11 (IE 11)

### ISSUE THREAD

**Issue by ilpssun** [paginagmbh/redmine_lightbox2#66]
When I use version 0.5.0 of the plugin in Redmine 4.0.4, the javascript is not working in IE 11.  It says that there is a syntax error in line 90 auf lightbox.js:

![grafik](https://user-images.githubusercontent.com/835280/61859057-a9ae2d00-aec7-11e9-95fe-f8e9f251c3db.png)

The same script is working fine in Firefox and Chrome/Chromium.

I'm no javascript expert – especially not regarding the differences between IE and FF/Chrome – so no clue as to what’s wrong with the line.

**Comment by tofi86** [comment]
Thanks for the report. It's fixed on branch `redmine-3.4` for Redmine 3.4 and on `master` for Redmine 4.x

I have not yet released a new version, but will soon.

**Comment by tofi86** [comment]
Sorry, the bugfix contained a bug 🙈 Now it's working and can be tested from the before mentioned branches.

**Comment by tainewoo** [comment]
image preview is ok now, but pdf preview still fails
