### ISSUE TITLE
v0.2.0 w/Redmine 3.0.0: Forum messages with attachments not supported

### ISSUE THREAD

**Issue by mazice** [paginagmbh/redmine_lightbox2#7]
Hello!, as of today, attachments on forum's messages seems to not be supported by this plugin. They open up in a new tab/get downloaded (standard behavior)

Is there any ETA on this? Any way to add this feature? (thanks!)

**Comment by tofi86** [comment]
Will have a look soon.

No ETA, dude... This is open source software which I develop in my spare time, no pressure, okay?!

**Comment by mazice** [comment]
Of course not! We're absolutely pleased about this plugin! I'm sorry if that sounded demanding (English is not my native lang)

I asked for ETA because I couldn't find the typical "todo list" that some repos on Git have, and didn't know if this was a planned feature. I'll be looking forward to this too, and post any helpful patches that I can find.

Best regards

**Comment by tofi86** [comment]
Actually, this was a bug since the Controller Class for boards changed in redmine 3.0.
Message Boards are supported again with `v0.2.1` now...
