### ISSUE TITLE
DMSF support: add id to image label

### ISSUE THREAD

**Issue by tofi86** [paginagmbh/redmine_lightbox2#73]
From @dinya at https://github.com/paginagmbh/redmine_lightbox2/issues/64#issuecomment-538729985:

> @tofi86
> 
> Could you add dmsf file ID to image label (something like `[<id>] <title>`)?
> 
> Use case. I found the image of interest in the slide preview and wanna link to it in some issue or wiki page with `{{dmsftn(id)}}`.
> 
> Currently I should remember the title (label), close preview and find ID by title in the files list. And then I can add the link. But the ID presence in the label in the bottom prevents this three unnecessary steps (remember, close and find).
> 
> What do you think?

**Comment by tofi86** [comment]
![grafik](https://user-images.githubusercontent.com/365118/68076421-775c7780-fdb4-11e9-91f9-e56a44bfd7c9.png)

Support added for both Redmine 4 (branch `master`) and Redmine 3.4 (branch `redmine-3.4`).

**Comment by dinya** [comment]
@tofi86 

I updated with the current ``redmine-3.4`` branch, but there is no ID in the image label,

![изображение](https://user-images.githubusercontent.com/2182222/68180403-662e8900-ffb5-11e9-8e2b-8d5b7e316a35.png)

My env:

Item | Version
-----|--------
Redmine version |                3.4.11.stable
Ruby version |                   2.3.3-p222 (2016-11-21) [x86_64-linux]
``redmine_lightbox2`` | 0.4.5
``redmine_dmsf`` | 1.6.2

**Comment by tofi86** [comment]
Did you run the plugin migrations?

**Comment by dinya** [comment]
Yes, as usual with

```sh
bundle exec rake redmine:plugins:migrate RAILS_ENV="production"
```

**Comment by tofi86** [comment]
Now I get it. it works in issues but not in DMS tab. sorry.

I added #74 for that.
