### ISSUE TITLE
IE11 download pdf

### ISSUE THREAD

**Issue by dl2v** [paginagmbh/redmine_lightbox2#80]
IE11 download pdf
Redmine version                4.0.5.stable
  Ruby version                   2.4.6-p354 (2019-04-01) [x86_64-linux]
  Rails version                  5.2.3

Redmine Lightbox 2 - 0.5.1

**Comment by tofi86** [comment]
Do you mean the preview isn't working in IE11? Did you try and have a look at the open issues? There's already an issue regarding IE11 (#71) so I'm closing this one here...
